### ISSUE TITLE
ConnectionError: Connection is closed

### ISSUE THREAD

**Issue by tosinek** [Irelander/mssql#1]
When I set up a new connection
`test = Sql.new(connString)`
`test.q(select)`
I get 
`{ [ConnectionError: Connection is closed.]`
`name: 'ConnectionError', message: 'Connection is closed.', code: 'ECONNCLOSED' }`
`connect success!`

The problem seems to be in asynchronicity. The Sql.new will start working on the connection, but the Sql.q is called too soon - before the connection is established. I have been trying to wrap it into Promises (no luck yet). Another solution would be to initialize the connection way earlier, the same way how the original Sql connection worked (it was established during package loading, which was enough time before you run the query).

**Comment by Irelander** [comment]
@tosinek 
Thank you for comment. and sorry for late reply.
You're right. The problem is async. 
So, I wrapped connection by Meteor.wrapAsync and then returning Object.
I feel sorry too late fixed.
